version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:15.7.0
    steps:
      - checkout
      - run:
          name: update-npm
          command: "sudo npm install -g npm@7"
      - restore_cache:
          key: npm-cache-v1-{{ checksum "package.json" }}
      - run:
          name: install-packages
          command: npm install
      - run:
          name: JS Lint
          command: npm run lint
      - run:
          name: JS Test Suite
          command: npm run test
          environment:
            JEST_JUNIT_OUTPUT: ./reports/junit/results.xml
      - store_artifacts:
          path: ./reports/junit
      - store_test_results:
          path: ./reports
      - save_cache:
          key: npm-cache-v1-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: build-project
          command: npm run generate:gh-pages
      - run:
          name: Install and configure dependencies
          command: |
            npm install gh-pages --save-dev
            git config user.email "l_martim@yahoo.com.br"
            git config user.name "lmartim"
      - add_ssh_keys:
          fingerprints:
            - "ca:e8:7d:7a:09:39:8d:c7:fc:69:8e:df:4e:40:96:04"
      - run:
          name: Deploy docs to gh-pages branch
          command: './node_modules/.bin/gh-pages --dotfiles --message "[skip ci] Updates" -d dist'
